### ISSUE TITLE
Missing lib/index.js after v3.0.0 update

### ISSUE THREAD

**Issue by domdepasquale** [autero1/action-terraform#359]
Seeing this error after upgrading to v3

<img width="886" alt="Screenshot 2024-02-20 at 11 41 37 AM" src="https://github.com/autero1/action-terraform/assets/7384087/376433d0-770f-4a23-8b1c-c5f3961aab45">

my usage:

```
      - uses: autero1/action-terraform@v3.0.0
        with:
          terraform-version: 1.6.6
```

**Comment by autero1** [comment]
My bad. That was due to the change in the release process. I'll fix asap.

**Comment by autero1** [comment]
Fixed in https://github.com/autero1/action-terraform/releases/tag/v3.0.1
You can also use `autero1/action-terraform@v3`
